### ISSUE TITLE
getpandas page should suggest pip over downloads (source/exes)

### ISSUE THREAD

**Issue by hayd** [pandas-dev/pandas-website#26]
At the moment the [getpandas page](http://pandas.pydata.org/getpandas.html) emphasises the download links over the installation instructions.

Pip is the recommended way, this should "jump out and punch you in the face", at least we should give it some more real estate. Perhaps shoving [the table](http://pandas.pydata.org/pandas-docs/stable/install.html#overview) here would help?

**Comment by TomAugspurger** [comment]
Fixed in https://github.com/pandas-dev/pandas-website/commit/035c9c6c271739f2eafaad641fa932d5bdfae8c8 :)
