### ISSUE TITLE
Tutorials - Practical data analysis with Python - Pages not Found

### ISSUE THREAD

**Issue by mariaclaudia** [pandas-dev/pandas-website#35]
From the Pandas web page:
http://pandas.pydata.org/pandas-docs/stable/tutorials.html
if you go to the section: "Practical data analysis with Python" 
The project http://wavedatalab.github.io/datawithpython and the links are not available.

**Comment by datapythonista** [comment]
Looks like it was a temporary problem, now they seem to be working fine.
