### ISSUE TITLE
Website is Down

### ISSUE THREAD

**Issue by MorganRodgers** [pandas-dev/pandas-website#38]
http://pandas.pydata.org/ is currently down.

**Comment by giacomov** [comment]
it has been down since at least yesterday night (Pacific Time)

**Comment by jreback** [comment]
seems ok to me. (just tried again).

**Comment by TomAugspurger** [comment]
Also working for me... In the meantime the dev docs at http://pandas-docs.github.io/pandas-docs-travis/ should still be working.

**Comment by MorganRodgers** [comment]
That's good to know Tom, thank you. I'm still unable to see if from my current workstation, but I've got confirmation from you good folks and also a few others that the site is in fact up. I think my university's IT folks might be doing something with our network at the moment.

Closing, and sorry for the false alarm.

**Comment by giacomov** [comment]
it still doesn't work for me, from my computer at Stanford nor from my computer at home... weird...

![image](https://cloud.githubusercontent.com/assets/5917371/22305355/0717dbb8-e2f0-11e6-9b22-ae5f2acb0f9e.png)

But thanks for the dev docs, I can use that in the meantime.

**Comment by jorisvandenbossche** [comment]
Also working fine for me

**Comment by giacomov** [comment]
I tried from computers in California, Maryland, and New Mexico and it doesn't work.

It works instead from a computer in Italy.

There must be some DNS problem somewhere... well, it will sort itself at some point.

Sorry for the spam,
