### ISSUE TITLE
Developers page out of data / should be removed

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas-website#40]
cfr https://github.com/pandas-dev/pandas/issues/15608#issuecomment-285770018

Page http://pandas.pydata.org/developers.html is out of date, and should simply redirect to the contributing guidelines in the documentation.

@toobaz Did you find this page by clicking on a link on the website somewhere? Or just by googling? 
As I think most of the links to contributing on the website (eg on http://pandas.pydata.org/community.html and http://pandas.pydata.org/getpandas.html#development-version) have been changed to link the the up to date guidelines in the documentation. But apparently the page itself has not been removed ..

**Comment by toobaz** [comment]
> @toobaz Did you find this page by clicking on a link on the website somewhere? Or just by googling?

The latter: it is the first result on Google for keys "pandas" "run" and "tests".

**Comment by jorisvandenbossche** [comment]
OK, made a PR to change the page with a redirect, so links keep working

**Comment by toobaz** [comment]
Great, thanks
