### ISSUE TITLE
Links in rc announce on pandas website not working

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas-website#49]
We had a lot of discussion about it, but it seems in the end you forgot to update the links to not use /stable/ ? 
Links here http://pandas.pydata.org/#v0-21-0-rc1-october-13-2017 still use stable and thus don't point to the correct location. They should use /version/0.21/ instead ?

**Comment by jorisvandenbossche** [comment]
cc @TomAugspurger

**Comment by TomAugspurger** [comment]
Sorry, I changed it for the announcement email but not here. Fixed in #50 .
