### ISSUE TITLE
Dead link on "talks" page

### ISSUE THREAD

**Issue by fuglede** [pandas-dev/pandas-website#54]
On https://pandas.pydata.org/talks.html, the PDF reference to *Data Structures for Statistical Computing in Python; presented at SciPy 2010*, http://www.jarrodmillman.com/scipy2010/pdfs/mckinney.pdf, only gives a 404.

**Comment by jorisvandenbossche** [comment]
@fuglede Thanks for the report! Yeah, in general the page is a bit outdated.

Specifically for this one, it seems to be available on the proceedings website of scipy: http://conference.scipy.org/proceedings/scipy2010/pdfs/mckinney.pdf

**Comment by datapythonista** [comment]
Looks like the link was updated.
