### ISSUE TITLE
No documentation for HDFStore class

### ISSUE THREAD

**Issue by hayderkhalid** [pandas-dev/pandas-website#56]
It looks like there is no documentation for the HDFStore class. I can't find anything in either the API reference or from Google.

There is a docstring of the __init__ of the constructor for this class, but it does not show. There is a blank line at [line 396](https://github.com/pandas-dev/pandas/blob/v0.21.0/pandas/io/pytables.py#L396)
 that might be messing with Sphinx or whatever you use to generate your docs.

Thanks

**Comment by TomAugspurger** [comment]
Thanks, the fix will go over in the main pandas repo, where the source for our docs is.

We're excluding it deliberately for now until we can fix some things in our doc build process.

**Comment by hayderkhalid** [comment]
Cool. Thanks for all your great work on pandas.
