### ISSUE TITLE
No PDF in Link for v0.23

### ISSUE THREAD

**Issue by cogmind** [pandas-dev/pandas-website#64]
The link to the PDF file is broken, both in the sidebar and the online doc frontpage. There seems to be no PDF:

`http://pandas.pydata.org/pandas-docs/stable/pandas.pdf`
`https://pandas.pydata.org/pandas-docs/version/0.23/pandas.pdf`
```

404 Not Found
nginx/1.10.3 (Ubuntu)

```

However, this links resolves:
https://pandas.pydata.org/pandas-docs/version/0.23/

```

This is what the HTML in the sidebar looks like:
<div class="tile">
    <h4>Release</h4>
    0.23.0 - May 2018 <br>
    <a href="https://pypi.org/project/pandas/#files">download</a>          //
    <a href="http://pandas.pydata.org/pandas-docs/stable/">docs</a> //
```

**Comment by TomAugspurger** [comment]
Thanks for the report. Should be fixed now.
