### ISSUE TITLE
Website remains to be not verified

### ISSUE THREAD

**Issue by stevenleeS0ht** [pandas-dev/pandas-website#75]
When visit the homepage of pandas, the web browser will report that the website is not verified. It would be awesome if it is verified by Let's Encrypt. This is free and easy.

See [here](https://letsencrypt.org/getting-started/) to find out the detailed instruction to get verified.

**Comment by TomAugspurger** [comment]
We serve it over https, we just don't auto-redirect http to https.

@aterrel do you know if this is something that would be handled by cloudflare?

**Comment by aterrel** [comment]
are ya'll hosted on ReadTheDocs?

Cloudflare is already hosting a cert with: https://pandas.pydata.org/ , but with RTD there isn't a good way to do the http->https redirect. For dask we just added a javascript function that checked the url protocol and did the redirect.

**Comment by TomAugspurger** [comment]
No IIRC we're on a VM you set up for us. I forget where it's hosted at.

**Comment by aterrel** [comment]
okay then that is on rackspace. Let me dig around the nginx settings.

**Comment by aterrel** [comment]
nginx updated. @stevenleeS0ht try again and see if it works for you.

**Comment by TomAugspurger** [comment]
Works for me. Thanks @aterrel!

**Comment by stevenleeS0ht** [comment]
@aterrel , It works. thanks.
