### ISSUE TITLE
Link with `pandas-dev/pandas`? - E.g., 1.0.1 => 1.0.4

### ISSUE THREAD

**Issue by SamuelMarks** [pandas-dev/pandas-website#87]
There's a big "What's new in 1.0.1" link in the top navbar, e.g., at https://pandas.pydata.org/docs/index.html

Maybe you should link it with
https://github.com/pandas-dev/pandas/releases

So that every new release generated a new static website? - Alternatively replace that navbar text with a little JavaScript to query the release on GitHub… or just remove the version number.

**Comment by TomAugspurger** [comment]
We've removed in it master: https://pandas.pydata.org/pandas-docs/dev/
